ln -s ~/dotfiles/i3 ~/.config/i3
ln -s ~/dotfiles/i3status ~/.config/i3status
ln -s ~/dotfiles/tmux ~/.config/tmux
ln -s ~/dotfiles/nvim ~/.config/nvim
ln -s ~/dotfiles/wallpapers ~/.config/wallpapers
ln -s ~/dotfiles/alacritty ~/.config/alacritty
ln -s ~/dotfiles/.Xresources ~
ln -s ~/dotfiles/.xinitrc ~
ln -s ~/dotfiles/.zshrc ~
